#!/bin/bash

#extract any of the following archive types
  case "$1" in
    *.zip)             unzip -d "$1"   ;;
    *.tar.bz2)         tar -xvjf "$1"  ;;
    *.tar.gz)          tar -xvzf "$1"  ;;
		*.tgz)						 tar -xvzf "$1"  ;;
    *.rar)             unrar x "$1"    ;;
    *.tbz2)            tar jxf "$1"    ;;
    *)                 echo "nope."
  esac
